[package]
name = "tribute-hir"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tribute-ast.workspace = true
tribute-core.workspace = true
serde.workspace = true
salsa.workspace = true