//! Cranelift native object file translation.
//!
//! This module provides functions for validating and emitting native object files
//! from TrunkIR modules that have already been lowered to the clif dialect.

use std::collections::HashMap;

use cranelift_codegen::ir::types as cl_types;
use cranelift_codegen::ir::{self as cl_ir, InstBuilder, UserFuncName};
use cranelift_codegen::settings::{self, Configurable};
use cranelift_codegen::{Context, isa};
use cranelift_frontend::{FunctionBuilder, FunctionBuilderContext};
use cranelift_module::{
    DataDescription, FuncId, Linkage, Module as CraneliftModule, default_libcall_names,
};
use cranelift_object::{ObjectBuilder, ObjectModule};
use target_lexicon::Triple;
use trunk_ir::Symbol;
use trunk_ir::context::IrContext;
use trunk_ir::dialect::clif as arena_clif;
use trunk_ir::ops::DialectOp;
use trunk_ir::refs::{BlockRef, OpRef, RegionRef};
use trunk_ir::rewrite::Module;

use crate::function::{FunctionTranslator, translate_signature, translate_type};
use crate::{CompilationError, CompilationResult, validate_clif_ir};

/// Mangle a TrunkIR symbol name for native linking.
///
/// Produces a fixed-length hash format inspired by Rust's name mangling:
/// `_trb_<last_component>_h<hash>`. The last path component is preserved
/// for debuggability, and a 16-hex-char hash of the full name ensures
/// uniqueness with predictable length.
fn mangle_native_name(name: &str) -> String {
    use std::hash::{Hash, Hasher};
    let mut hasher = rustc_hash::FxHasher::default();
    name.hash(&mut hasher);
    let hash = hasher.finish();

    let last = name.rsplit("::").next().unwrap_or(name);
    format!("_trb_{}_h{:016x}", last, hash)
}

/// Information collected about RTTI release functions for code emission.
struct RttiEmitInfo {
    /// FuncId for `__tribute_deep_release` (always present).
    deep_release_func_id: FuncId,
    /// DataId for the RTTI function pointer table (None if no release functions exist).
    rtti_table_data_id: Option<cranelift_module::DataId>,
    /// Mapping from rtti_idx to the corresponding release function's FuncId.
    release_functions: HashMap<u32, FuncId>,
    /// Maximum rtti_idx seen (determines table size). 0 if no release functions.
    max_rtti_idx: u32,
}

/// Prefix for per-type release functions generated by the RTTI pass.
const RELEASE_FN_PREFIX: &str = "__tribute_release_";

/// Collect release functions from func_ids and declare RTTI infrastructure.
///
/// Scans `func_ids` for functions matching `__tribute_release_<N>` pattern,
/// then declares `__tribute_deep_release` and the RTTI table.
fn collect_and_declare_rtti(
    obj_module: &mut ObjectModule,
    func_ids: &mut HashMap<Symbol, FuncId>,
    call_conv: cranelift_codegen::isa::CallConv,
) -> CompilationResult<RttiEmitInfo> {
    let ptr_ty = obj_module.target_config().pointer_type();

    // Scan func_ids for __tribute_release_<N> functions
    let mut release_functions: HashMap<u32, FuncId> = HashMap::new();
    let mut max_rtti_idx: u32 = 0;

    for (sym, &func_id) in func_ids.iter() {
        let name = sym.to_string();
        if let Some(suffix) = name.strip_prefix(RELEASE_FN_PREFIX)
            && let Ok(idx) = suffix.parse::<u32>()
        {
            release_functions.insert(idx, func_id);
            max_rtti_idx = max_rtti_idx.max(idx);
        }
    }

    // Declare __tribute_deep_release(ptr, size) -> void
    let mut deep_release_sig = cl_ir::Signature::new(call_conv);
    deep_release_sig.params.push(cl_ir::AbiParam::new(ptr_ty));
    deep_release_sig
        .params
        .push(cl_ir::AbiParam::new(cl_types::I64));
    // no return value

    let deep_release_sym = Symbol::new("__tribute_deep_release");
    let deep_release_func_id = obj_module
        .declare_function("__tribute_deep_release", Linkage::Export, &deep_release_sig)
        .map_err(|e| CompilationError::codegen(format!("{e}")))?;
    func_ids.insert(deep_release_sym, deep_release_func_id);

    // Declare RTTI table if we have release functions
    let rtti_table_data_id = if !release_functions.is_empty() {
        let data_id = obj_module
            .declare_data("__tribute_rtti_table", Linkage::Local, false, false)
            .map_err(|e| CompilationError::codegen(format!("{e}")))?;
        Some(data_id)
    } else {
        None
    };

    Ok(RttiEmitInfo {
        deep_release_func_id,
        rtti_table_data_id,
        release_functions,
        max_rtti_idx,
    })
}

/// Define the RTTI function pointer table and the `__tribute_deep_release` dispatch function.
fn define_rtti_infrastructure(
    obj_module: &mut ObjectModule,
    func_ids: &HashMap<Symbol, FuncId>,
    rtti_info: &RttiEmitInfo,
    call_conv: cranelift_codegen::isa::CallConv,
) -> CompilationResult<()> {
    let ptr_ty = obj_module.target_config().pointer_type();
    let ptr_size = ptr_ty.bytes();

    // Define RTTI table if it exists
    if let Some(data_id) = rtti_info.rtti_table_data_id {
        let table_size = (rtti_info.max_rtti_idx + 1) as usize;
        let mut data_desc = DataDescription::new();
        // Use define() with zero-filled buffer instead of define_zeroinit() to ensure
        // the table is placed in a data section (not BSS), since we add relocations
        // for function pointers below. BSS + relocations causes linker crashes on macOS.
        let table_bytes = vec![0u8; table_size * ptr_size as usize];
        data_desc.define(table_bytes.into_boxed_slice());
        data_desc.set_align(ptr_size as u64);

        for (&rtti_idx, &release_func_id) in &rtti_info.release_functions {
            let fref = obj_module.declare_func_in_data(release_func_id, &mut data_desc);
            data_desc.write_function_addr(rtti_idx * ptr_size, fref);
        }

        obj_module
            .define_data(data_id, &data_desc)
            .map_err(|e| CompilationError::codegen(format!("{e}")))?;
    }

    // Define __tribute_deep_release(ptr, size)
    let mut deep_release_sig = cl_ir::Signature::new(call_conv);
    deep_release_sig.params.push(cl_ir::AbiParam::new(ptr_ty));
    deep_release_sig
        .params
        .push(cl_ir::AbiParam::new(cl_types::I64));

    let mut cl_func = cl_ir::Function::with_name_signature(
        UserFuncName::user(0, rtti_info.deep_release_func_id.as_u32()),
        deep_release_sig,
    );

    // Look up __tribute_dealloc FuncId
    let dealloc_sym = Symbol::new("__tribute_dealloc");
    let dealloc_func_id = func_ids[&dealloc_sym];
    let dealloc_fref = obj_module.declare_func_in_func(dealloc_func_id, &mut cl_func);

    let mut fb_ctx = FunctionBuilderContext::new();
    {
        let mut builder = FunctionBuilder::new(&mut cl_func, &mut fb_ctx);

        if rtti_info.release_functions.is_empty() {
            // No release functions: always do shallow dealloc
            build_shallow_only_deep_release(&mut builder, ptr_ty, dealloc_fref);
        } else {
            // Has release functions: dispatch via RTTI table
            let rtti_table_data_id = rtti_info.rtti_table_data_id.unwrap();
            let rtti_table_gv = obj_module.declare_data_in_func(rtti_table_data_id, builder.func);

            // Declare release function signature for call_indirect
            let mut release_sig = cl_ir::Signature::new(call_conv);
            release_sig.params.push(cl_ir::AbiParam::new(ptr_ty));
            let release_sig_ref = builder.import_signature(release_sig);

            build_dispatching_deep_release(
                &mut builder,
                ptr_ty,
                dealloc_fref,
                rtti_table_gv,
                release_sig_ref,
            );
        }

        builder.seal_all_blocks();
        builder.finalize();
    }

    let mut ctx = Context::for_function(cl_func);
    obj_module
        .define_function(rtti_info.deep_release_func_id, &mut ctx)
        .map_err(|e| CompilationError::codegen(format!("{e}")))?;

    Ok(())
}

/// Build `__tribute_deep_release` body when there are no release functions.
///
/// Simply computes raw_ptr and calls `__tribute_dealloc(raw_ptr, alloc_size)`.
fn build_shallow_only_deep_release(
    builder: &mut FunctionBuilder,
    ptr_ty: cl_types::Type,
    dealloc_fref: cl_ir::FuncRef,
) {
    let entry = builder.create_block();
    builder.append_block_params_for_function_params(entry);
    builder.switch_to_block(entry);

    let payload_ptr = builder.block_params(entry)[0];
    let alloc_size = builder.block_params(entry)[1];

    // raw_ptr = payload_ptr - 8
    let neg8 = builder.ins().iconst(ptr_ty, -8);
    let raw_ptr = builder.ins().iadd(payload_ptr, neg8);

    // __tribute_dealloc(raw_ptr, alloc_size)
    builder.ins().call(dealloc_fref, &[raw_ptr, alloc_size]);

    builder.ins().return_(&[]);
}

/// Build `__tribute_deep_release` body with RTTI table dispatch.
///
/// ```text
/// entry(payload_ptr, alloc_size):
///   raw_ptr = payload_ptr - 8
///   rtti_idx = load i32 from raw_ptr+4
///   entry_offset = rtti_idx * ptr_size
///   release_fn = load ptr from rtti_table[entry_offset]
///   if release_fn == null: goto shallow
///   else: goto deep
///
/// shallow:
///   __tribute_dealloc(raw_ptr, alloc_size)
///   return
///
/// deep:
///   call_indirect release_fn(payload_ptr)
///   return
/// ```
fn build_dispatching_deep_release(
    builder: &mut FunctionBuilder,
    ptr_ty: cl_types::Type,
    dealloc_fref: cl_ir::FuncRef,
    rtti_table_gv: cl_ir::GlobalValue,
    release_sig_ref: cl_ir::SigRef,
) {
    let entry = builder.create_block();
    let shallow_block = builder.create_block();
    let deep_block = builder.create_block();

    builder.append_block_params_for_function_params(entry);
    builder.switch_to_block(entry);

    let payload_ptr = builder.block_params(entry)[0];
    let alloc_size = builder.block_params(entry)[1];

    // raw_ptr = payload_ptr - 8
    let neg8 = builder.ins().iconst(ptr_ty, -8);
    let raw_ptr = builder.ins().iadd(payload_ptr, neg8);

    // rtti_idx = load i32 from raw_ptr + 4
    let rtti_idx = builder
        .ins()
        .load(cl_types::I32, cl_ir::MemFlags::trusted(), raw_ptr, 4);

    // entry_offset = uextend(rtti_idx) * ptr_size
    let rtti_idx_64 = builder.ins().uextend(ptr_ty, rtti_idx);
    let ptr_size_val = builder.ins().iconst(ptr_ty, ptr_ty.bytes() as i64);
    let entry_offset = builder.ins().imul(rtti_idx_64, ptr_size_val);

    // table_base = global_value for rtti_table
    let table_base = builder.ins().global_value(ptr_ty, rtti_table_gv);

    // entry_addr = table_base + entry_offset
    let entry_addr = builder.ins().iadd(table_base, entry_offset);

    // release_fn = load ptr from entry_addr
    let release_fn = builder
        .ins()
        .load(ptr_ty, cl_ir::MemFlags::trusted(), entry_addr, 0);

    // if release_fn == null: shallow, else: deep
    let null = builder.ins().iconst(ptr_ty, 0);
    let is_null = builder
        .ins()
        .icmp(cl_ir::condcodes::IntCC::Equal, release_fn, null);
    builder
        .ins()
        .brif(is_null, shallow_block, &[], deep_block, &[]);

    // shallow_block: __tribute_dealloc(raw_ptr, alloc_size); return
    builder.switch_to_block(shallow_block);
    builder.ins().call(dealloc_fref, &[raw_ptr, alloc_size]);
    builder.ins().return_(&[]);

    // deep_block: call_indirect release_fn(payload_ptr); return
    builder.switch_to_block(deep_block);
    builder
        .ins()
        .call_indirect(release_sig_ref, release_fn, &[payload_ptr]);
    builder.ins().return_(&[]);
}

/// Read-only data section entry for native code generation.
pub struct RodataEntry {
    /// Symbol name for this data section (e.g., `__tribute_rodata_0`).
    pub symbol: Symbol,
    /// Raw byte content.
    pub data: Vec<u8>,
}

/// Emit a native object file from a lowered TrunkIR module.
///
/// This function assumes the module has already been lowered to clif dialect
/// and all type conversions have been resolved. It:
/// 1. Validates the IR (checks for non-clif ops)
/// 2. Emits native code via Cranelift
///
/// `rodata` provides read-only data sections that can be referenced via
/// `clif.symbol_addr` operations.
///
/// For Tribute-specific compilation (including lowering from high-level IR),
/// use the orchestration in the main crate's pipeline.
pub fn emit_module_to_native(
    ctx: &IrContext,
    module: Module,
    rodata: &[RodataEntry],
) -> CompilationResult<Vec<u8>> {
    validate_clif_ir(ctx, module)?;
    emit_module_impl(ctx, module, rodata)
}

fn emit_module_impl(
    ctx: &IrContext,
    module: Module,
    rodata: &[RodataEntry],
) -> CompilationResult<Vec<u8>> {
    // 1. ISA setup — use host triple
    let triple = Triple::host();
    let mut flag_builder = settings::builder();
    flag_builder
        .set("is_pic", "true")
        .map_err(|e| CompilationError::codegen(format!("{e}")))?;
    let isa_builder = isa::lookup(triple).map_err(|e| CompilationError::codegen(format!("{e}")))?;
    let isa = isa_builder
        .finish(settings::Flags::new(flag_builder))
        .map_err(|e| CompilationError::codegen(format!("{e}")))?;
    let call_conv = isa.default_call_conv();

    // 2. ObjectModule creation
    let module_name = module
        .name(ctx)
        .map(|s| s.to_string())
        .unwrap_or_else(|| "unnamed".to_string());
    let obj_builder = ObjectBuilder::new(isa, module_name, default_libcall_names())
        .map_err(|e| CompilationError::codegen(format!("{e}")))?;
    let mut obj_module = ObjectModule::new(obj_builder);
    let ptr_ty = obj_module.target_config().pointer_type();

    // 3. First pass — declare all functions
    let mut func_ids: HashMap<Symbol, cranelift_module::FuncId> = HashMap::new();
    let all_func_ops = collect_clif_funcs(ctx, module);

    for &func_op in &all_func_ops {
        let func_wrapped = arena_clif::Func::from_op(ctx, func_op)
            .map_err(|_| CompilationError::codegen("expected clif.func op"))?;
        let name_sym = func_wrapped.sym_name(ctx);
        let func_type_ref = func_wrapped.r#type(ctx);

        let op_data = ctx.op(func_op);
        let has_abi = op_data.attributes.contains_key(&Symbol::new("abi"));
        let linkage = if name_sym == "main" {
            Linkage::Export
        } else if has_abi {
            Linkage::Import
        } else {
            Linkage::Local
        };

        // Skip imported functions whose types can't be translated to Cranelift
        // (e.g., prelude extern functions using core.bytes that are never called).
        let sig = match translate_signature(ctx, func_type_ref, call_conv, ptr_ty) {
            Ok(sig) => sig,
            Err(_) if has_abi => continue,
            Err(e) => return Err(e),
        };

        let linker_name = if linkage == Linkage::Local {
            name_sym.with_str(mangle_native_name)
        } else {
            name_sym.to_string()
        };

        let func_id = obj_module
            .declare_function(&linker_name, linkage, &sig)
            .map_err(|e| CompilationError::codegen(format!("{e}")))?;
        func_ids.insert(name_sym, func_id);
    }

    // 3b. Declare runtime functions
    declare_runtime_functions(&mut obj_module, &mut func_ids, call_conv)?;

    // 3c. RTTI infrastructure
    let rtti_info = collect_and_declare_rtti(&mut obj_module, &mut func_ids, call_conv)?;

    // 3d. Declare and define rodata sections
    let mut data_ids: HashMap<Symbol, cranelift_module::DataId> = HashMap::new();
    for entry in rodata {
        let data_id = obj_module
            .declare_data(
                &entry.symbol.to_string(),
                Linkage::Local,
                false, // not writable
                false, // not TLS
            )
            .map_err(|e| CompilationError::codegen(format!("{e}")))?;

        let mut data_desc = DataDescription::new();
        data_desc.define(entry.data.clone().into_boxed_slice());
        data_desc.set_align(1); // byte-aligned rodata
        obj_module
            .define_data(data_id, &data_desc)
            .map_err(|e| CompilationError::codegen(format!("{e}")))?;

        data_ids.insert(entry.symbol, data_id);
    }

    // 4. Second pass — define functions
    let mut fb_ctx = FunctionBuilderContext::new();

    for &func_op in &all_func_ops {
        let op_data = ctx.op(func_op);
        let has_abi = op_data.attributes.contains_key(&Symbol::new("abi"));
        if has_abi {
            continue;
        }

        let func_wrapped = arena_clif::Func::from_op(ctx, func_op)
            .map_err(|_| CompilationError::codegen("expected clif.func op"))?;
        let name_sym = func_wrapped.sym_name(ctx);
        let func_type_ref = func_wrapped.r#type(ctx);

        let sig = translate_signature(ctx, func_type_ref, call_conv, ptr_ty)?;
        let func_id = func_ids[&name_sym];

        let mut cl_func =
            cl_ir::Function::with_name_signature(UserFuncName::user(0, func_id.as_u32()), sig);

        // Declare all known functions as FuncRefs
        let mut func_refs: HashMap<Symbol, cl_ir::FuncRef> = HashMap::new();
        for (&sym, &fid) in &func_ids {
            let fref = obj_module.declare_func_in_func(fid, &mut cl_func);
            func_refs.insert(sym, fref);
        }

        // Declare all data sections as GlobalValues
        let mut data_refs: HashMap<Symbol, cl_ir::GlobalValue> = HashMap::new();
        for (&sym, &did) in &data_ids {
            let gv = obj_module.declare_data_in_func(did, &mut cl_func);
            data_refs.insert(sym, gv);
        }

        // Build the function body
        {
            let builder = FunctionBuilder::new(&mut cl_func, &mut fb_ctx);
            let mut translator =
                FunctionTranslator::new(ctx, builder, &func_refs, &data_refs, call_conv, ptr_ty);

            let func_body = func_wrapped.body(ctx);
            let body_region = ctx.region(func_body);
            let ir_blocks: &[BlockRef] = &body_region.blocks;

            // Phase 1: Create all Cranelift blocks upfront
            let entry_block = translator.builder.create_block();
            translator
                .builder
                .append_block_params_for_function_params(entry_block);

            if let Some(&ir_entry_block) = ir_blocks.first() {
                translator.block_map.insert(ir_entry_block, entry_block);
            }

            // Create Cranelift blocks for non-entry IR blocks
            for &ir_block in ir_blocks.iter().skip(1) {
                let cl_block = translator.builder.create_block();
                let ir_args = ctx.block_args(ir_block);
                for &arg_val in ir_args {
                    let arg_ty = ctx.value_ty(arg_val);
                    let cl_ty = translate_type(ctx, arg_ty, ptr_ty)?;
                    translator.builder.append_block_param(cl_block, cl_ty);
                }
                translator.block_map.insert(ir_block, cl_block);
            }

            // Phase 2: Translate operations in each block
            for &ir_block in ir_blocks {
                let cl_block = translator.lookup_block(ir_block)?;
                translator.builder.switch_to_block(cl_block);

                // Map block arguments to Cranelift block params
                let cl_params: Vec<_> = translator.builder.block_params(cl_block).to_vec();
                let ir_args = ctx.block_args(ir_block);
                let ir_arg_count = ir_args.len();
                if ir_arg_count != cl_params.len() {
                    let is_entry = ir_blocks.first() == Some(&ir_block);
                    let ir_arg_types: Vec<String> = ir_args
                        .iter()
                        .map(|&a| {
                            let ty = ctx.value_ty(a);
                            let td = ctx.types.get(ty);
                            format!("{}.{}", td.dialect, td.name)
                        })
                        .collect();
                    let func_ty_data = ctx.types.get(func_type_ref);
                    let func_ty_params: Vec<String> = func_ty_data
                        .params
                        .iter()
                        .map(|&p| {
                            let td = ctx.types.get(p);
                            format!("{}.{}", td.dialect, td.name)
                        })
                        .collect();
                    return Err(CompilationError::codegen(format!(
                        "block arg count mismatch: TrunkIR block has {} args ({:?}) but Cranelift block has {} params (function: {}, entry: {}, func_type_params: {:?})",
                        ir_arg_count,
                        ir_arg_types,
                        cl_params.len(),
                        name_sym,
                        is_entry,
                        func_ty_params,
                    )));
                }
                for (i, &cl_param) in cl_params.iter().enumerate() {
                    let ir_arg = ir_args[i];
                    translator.values.insert(ir_arg, cl_param);
                }

                // Translate each operation in this block
                let block_ops = ctx.block(ir_block).ops.clone();
                for &ir_op in &block_ops {
                    translator.translate_op(ir_op).map_err(|e| {
                        let op_data = ctx.op(ir_op);
                        CompilationError::codegen(format!(
                            "{e} (in {}.{} of function {})",
                            op_data.dialect, op_data.name, name_sym,
                        ))
                    })?;
                }
            }

            translator.builder.seal_all_blocks();
            translator.builder.finalize();
        }

        // Compile the function via Cranelift
        let mut cr_ctx = Context::for_function(cl_func);

        obj_module
            .define_function(func_id, &mut cr_ctx)
            .map_err(|e| CompilationError::codegen(format!("Function {} {e:?}", name_sym)))?;
    }

    // 4b. Define RTTI table and __tribute_deep_release
    define_rtti_infrastructure(&mut obj_module, &func_ids, &rtti_info, call_conv)?;

    // 5. Emit object file
    let product = obj_module.finish();
    let bytes = product
        .emit()
        .map_err(|e| CompilationError::codegen(format!("{e}")))?;

    Ok(bytes)
}

/// Collect all `clif.func` operations from a Module.
fn collect_clif_funcs(ctx: &IrContext, module: Module) -> Vec<OpRef> {
    let mut funcs = Vec::new();
    if let Some(body) = module.body(ctx) {
        collect_clif_funcs_from_region(ctx, body, &mut funcs);
    }
    funcs
}

fn collect_clif_funcs_from_region(ctx: &IrContext, region: RegionRef, funcs: &mut Vec<OpRef>) {
    let region_data = ctx.region(region);
    for &block in &region_data.blocks {
        let block_data = ctx.block(block);
        for &op in &block_data.ops {
            if arena_clif::Func::from_op(ctx, op).is_ok() {
                funcs.push(op);
            } else {
                let op_data = ctx.op(op);
                if op_data.dialect == Symbol::new("core") && op_data.name == Symbol::new("module") {
                    for &nested_region in &op_data.regions {
                        collect_clif_funcs_from_region(ctx, nested_region, funcs);
                    }
                }
            }
        }
    }
}

/// Declare runtime functions that are imported (provided by the linker).
///
/// Currently declares:
/// - `__tribute_alloc(i64) -> ptr`: heap allocation (malloc wrapper)
/// - `__tribute_dealloc(ptr, i64)`: heap deallocation (free wrapper)
///
/// These use `Import` linkage so they can be overridden at link time
/// with custom allocator implementations.
fn declare_runtime_functions(
    obj_module: &mut ObjectModule,
    func_ids: &mut HashMap<Symbol, cranelift_module::FuncId>,
    call_conv: isa::CallConv,
) -> CompilationResult<()> {
    let ptr_ty = obj_module.target_config().pointer_type();
    let i64_ty = cranelift_codegen::ir::types::I64;

    // __tribute_alloc(size: i64) -> ptr
    let mut alloc_sig = cl_ir::Signature::new(call_conv);
    alloc_sig.params.push(cl_ir::AbiParam::new(i64_ty));
    alloc_sig.returns.push(cl_ir::AbiParam::new(ptr_ty));

    let alloc_sym = Symbol::new("__tribute_alloc");
    if let std::collections::hash_map::Entry::Vacant(e) = func_ids.entry(alloc_sym) {
        let func_id = obj_module
            .declare_function("__tribute_alloc", Linkage::Import, &alloc_sig)
            .map_err(|e| CompilationError::codegen(format!("{e}")))?;
        e.insert(func_id);
    }

    // __tribute_dealloc(ptr: ptr, size: i64)
    let mut dealloc_sig = cl_ir::Signature::new(call_conv);
    dealloc_sig.params.push(cl_ir::AbiParam::new(ptr_ty));
    dealloc_sig.params.push(cl_ir::AbiParam::new(i64_ty));

    let dealloc_sym = Symbol::new("__tribute_dealloc");
    if let std::collections::hash_map::Entry::Vacant(e) = func_ids.entry(dealloc_sym) {
        let func_id = obj_module
            .declare_function("__tribute_dealloc", Linkage::Import, &dealloc_sig)
            .map_err(|e| CompilationError::codegen(format!("{e}")))?;
        e.insert(func_id);
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mangle_native_name() {
        // Pin exact mangled names so any hash-function change is caught.
        insta::assert_snapshot!(mangle_native_name("main"), @"_trb_main_h0b47e05e4c5c1745");
        insta::assert_snapshot!(mangle_native_name("Foo::bar"), @"_trb_bar_h35024d165ec188ad");
        insta::assert_snapshot!(mangle_native_name("std::List::map"), @"_trb_map_hec4bdfe12f592d9c");

        // Same input → same output (deterministic)
        assert_eq!(mangle_native_name("main"), mangle_native_name("main"));
    }
}
