//! Dialect operation and type utilities.
//!
//! Provides `DialectOp` and `DialectType` traits for arena-based
//! dialect operation and type wrappers, plus `ConversionError` and the
//! `raw_ident_str!` macro.
//! Trait definitions are generated by `trunk_ir_macros::arena_dialect!`.

use super::context::IrContext;
use super::refs::{OpRef, TypeRef};

/// Convert an identifier token into a clean string, handling raw identifiers.
///
/// Rust requires the `r#` prefix for reserved keywords like `type` or `yield`
/// when used as identifiers. This macro strips that prefix at expansion time
/// so the IR stores clean names like "type" instead of "r#type".
#[doc(hidden)]
#[macro_export]
macro_rules! raw_ident_str {
    (r#type) => {
        "type"
    };
    (r#const) => {
        "const"
    };
    (r#use) => {
        "use"
    };
    (r#yield) => {
        "yield"
    };
    (r#return) => {
        "return"
    };
    (r#if) => {
        "if"
    };
    (r#else) => {
        "else"
    };
    (r#loop) => {
        "loop"
    };
    (r#case) => {
        "case"
    };
    (r#struct) => {
        "struct"
    };
    (r#enum) => {
        "enum"
    };
    (r#break) => {
        "break"
    };
    (r#continue) => {
        "continue"
    };
    (r#ref) => {
        "ref"
    };
    ($ident:ident) => {
        stringify!($ident)
    };
}

/// Error when converting an Operation to a dialect-specific type.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConversionError {
    /// Operation name doesn't match expected dialect.operation.
    WrongOperation {
        expected: &'static str,
        actual: String,
    },
    /// Missing required attribute.
    MissingAttribute(&'static str),
    /// Attribute has wrong type.
    WrongAttributeType(&'static str),
    /// Missing result type.
    MissingResult,
    /// Missing region.
    MissingRegion,
    /// Missing or insufficient successors.
    MissingSuccessor,
    /// Wrong number of operands.
    WrongOperandCount { expected: usize, actual: usize },
}

/// Trait for arena-based dialect operation wrappers.
pub trait DialectOp: Sized + Copy {
    const DIALECT_NAME: &'static str;
    const OP_NAME: &'static str;

    fn from_op(ctx: &IrContext, op: OpRef) -> Result<Self, ConversionError>;
    fn op_ref(&self) -> OpRef;

    fn matches(ctx: &IrContext, op: OpRef) -> bool {
        let data = ctx.op(op);
        data.dialect == crate::Symbol::new(Self::DIALECT_NAME)
            && data.name == crate::Symbol::new(Self::OP_NAME)
    }
}

/// Trait for arena-based dialect type wrappers.
pub trait DialectType: Sized + Copy {
    const DIALECT_NAME: &'static str;
    const TYPE_NAME: &'static str;

    fn from_type_ref(ctx: &IrContext, ty: TypeRef) -> Option<Self>;
    fn as_type_ref(&self) -> TypeRef;

    fn matches(ctx: &IrContext, ty: TypeRef) -> bool {
        let data = ctx.types.get(ty);
        data.dialect == crate::Symbol::new(Self::DIALECT_NAME)
            && data.name == crate::Symbol::new(Self::TYPE_NAME)
    }
}
