//! Interned symbols and block identifiers.
//!
//! These types are Salsa-independent core primitives used throughout the IR.

use std::borrow::Cow;
use std::sync::atomic::{AtomicU64, Ordering};

use smallvec::SmallVec;

// ============================================================================
// Interned Types
// ============================================================================

mod atom {
    #![allow(dead_code, unused_macros)]
    include!(concat!(env!("OUT_DIR"), "/symbol_atom.rs"));
}
use atom::SymbolAtom;

/// Interned symbol for efficient comparison of names (functions, variables, fields, etc.)
///
/// EXPERIMENT: backed by `string_cache::Atom`. An atom is 8 bytes and is
/// one of: a name of at most 7 bytes stored inline, an index into the static
/// set generated by `build.rs`, or a reference-counted entry of the global
/// dynamic set. Cloning and dropping a dynamic atom updates its count, so
/// `Symbol` is `Clone` but not `Copy`.
///
/// Ordering is based on the underlying string content,
/// so that key-ordered collections such as `AttributeMap` iterate deterministically.
#[derive(Clone, PartialEq, Eq)]
#[cfg_attr(feature = "salsa", derive(salsa::SalsaValue))]
pub struct Symbol(SymbolAtom);

impl std::hash::Hash for Symbol {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

impl PartialOrd for Symbol {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for Symbol {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        if self.0 == other.0 {
            return std::cmp::Ordering::Equal;
        }
        self.as_str().cmp(other.as_str())
    }
}

impl std::fmt::Debug for Symbol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Symbol({:?})", self.as_str())
    }
}

impl Symbol {
    /// Intern a static string and return its symbol.
    pub fn new(text: &'static str) -> Self {
        Symbol(SymbolAtom::from(text))
    }

    /// Intern a string and return its symbol.
    pub fn from_dynamic(text: &str) -> Self {
        Symbol(SymbolAtom::from(text))
    }

    /// The symbol's text.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Access the symbol's text with zero-copy.
    ///
    /// ```
    /// use trunk_ir::Symbol;
    /// let symbol = Symbol::new("something");
    /// assert!(symbol.with_str(|s| s == "something"));
    /// ```
    pub fn with_str<R>(&self, f: impl FnOnce(&str) -> R) -> R {
        f(self.as_str())
    }

    /// Whether the symbol is stored without a dynamic-set entry.
    pub fn is_static_or_inline(&self) -> bool {
        !self.0.is_dynamic()
    }
}

impl From<&'static str> for Symbol {
    fn from(text: &'static str) -> Self {
        Symbol::new(text)
    }
}

impl From<Cow<'_, str>> for Symbol {
    fn from(text: Cow<'_, str>) -> Self {
        Symbol::from_dynamic(&text)
    }
}

/// Helper macro for declaring multiple symbol helpers at once.
///
/// # Example
/// ```
/// use trunk_ir::symbols;
///
/// symbols! {
///     ATTR_NAME => "name",
///     ATTR_TYPE => "type",
///     #[allow(dead_code)]
///     ATTR_UNUSED => "unused",
/// }
/// ```
#[macro_export]
macro_rules! symbols {
    ($($(#[$attr:meta])* $name:ident => $text:literal),* $(,)?) => {
        $(
            $(#[$attr])*
            #[allow(non_snake_case)]
            #[inline]
            pub fn $name() -> $crate::Symbol {
                $crate::Symbol::new($text)
            }
        )*
    };
}

// Convenient comparison with &str
impl PartialEq<str> for Symbol {
    fn eq(&self, other: &str) -> bool {
        self.with_str(|s| s == other)
    }
}

impl PartialEq<&str> for Symbol {
    fn eq(&self, other: &&str) -> bool {
        self.with_str(|s| s == *other)
    }
}

impl PartialEq<Symbol> for str {
    fn eq(&self, other: &Symbol) -> bool {
        other.with_str(|s| s == self)
    }
}

impl PartialEq<Symbol> for &str {
    fn eq(&self, other: &Symbol) -> bool {
        other.with_str(|s| s == *self)
    }
}

// For Display (uses with_str for zero-copy)
impl std::fmt::Display for Symbol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.with_str(|s| write!(f, "{}", s))
    }
}

// ============================================================================
// Block Identity
// ============================================================================

/// Global counter for generating unique block IDs.
static NEXT_BLOCK_ID: AtomicU64 = AtomicU64::new(1);

/// Stable block identifier that survives block recreation.
///
/// Unlike `Block` (which is a Salsa tracked struct with identity tied to creation),
/// `BlockId` is a simple u64 that can be preserved when a block is recreated
/// during IR transformations. This allows block arguments to maintain stable
/// identity across rewrites.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct BlockId(pub u64);

impl BlockId {
    /// Generate a fresh unique block ID.
    pub fn fresh() -> Self {
        BlockId(NEXT_BLOCK_ID.fetch_add(1, Ordering::Relaxed))
    }
}

// ============================================================================
// Small vector type aliases
// ============================================================================

/// Small vector for values tracked by Salsa framework.
pub type IdVec<T> = SmallVec<[T; 2]>;

/// Small vector for symbols.
pub type SymbolVec = SmallVec<[Symbol; 4]>;
