//! Interned symbols and block identifiers.
//!
//! These types are Salsa-independent core primitives used throughout the IR.

use std::borrow::Cow;
use std::sync::atomic::{AtomicU64, Ordering};

use smallvec::SmallVec;

// ============================================================================
// Interned Types
// ============================================================================

#[doc(hidden)]
pub mod atom {
    #![allow(dead_code, unused_macros)]
    include!(concat!(env!("OUT_DIR"), "/symbol_atom.rs"));
    pub use symbol_atom as literal;
}
use atom::SymbolAtom;

/// Interned symbol for efficient comparison of names (functions, variables, fields, etc.)
///
/// A symbol is an 8-byte `string_cache::Atom` in one of three forms:
///
/// - a name of at most 7 bytes, stored inline;
/// - an index into the static set of trunk-ir's own names, generated by
///   `build.rs`;
/// - a reference-counted entry of the process-wide dynamic set, which is
///   removed when its last symbol is dropped.
///
/// Equality compares the 8 bytes and hashing uses the atom's precomputed
/// hash. Ordering compares the text, so that key-ordered collections such as
/// `AttributeMap` iterate deterministically. Cloning or dropping a dynamic
/// symbol updates its count, so `Symbol` is `Clone` but not `Copy`; borrow
/// it where the name is only read.
#[derive(Clone, PartialEq, Eq)]
#[cfg_attr(feature = "salsa", derive(salsa::SalsaValue))]
pub struct Symbol(SymbolAtom);

impl std::hash::Hash for Symbol {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

impl PartialOrd for Symbol {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for Symbol {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        if self.0 == other.0 {
            return std::cmp::Ordering::Equal;
        }
        self.as_str().cmp(other.as_str())
    }
}

impl std::fmt::Debug for Symbol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Symbol({:?})", self.as_str())
    }
}

impl Symbol {
    /// Intern a string, using the static set or inline representation when possible.
    pub fn new(text: &str) -> Self {
        Symbol(SymbolAtom::from(text))
    }

    /// Wrap a compile-time atom produced by `symbol!`.
    #[doc(hidden)]
    pub const fn __from_atom(atom: SymbolAtom) -> Self {
        Self(atom)
    }

    /// The symbol's text.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Access the symbol's text with zero-copy.
    ///
    /// ```
    /// use trunk_ir::Symbol;
    /// let symbol = Symbol::new("something");
    /// assert!(symbol.with_str(|s| s == "something"));
    /// ```
    pub fn with_str<R>(&self, f: impl FnOnce(&str) -> R) -> R {
        f(self.as_str())
    }

    /// Whether the symbol is stored without a dynamic-set entry.
    pub fn is_static_or_inline(&self) -> bool {
        !self.0.is_dynamic()
    }
}

/// The number of names currently held by the dynamic set.
#[cfg(feature = "symbol-stats")]
pub fn live_dynamic_symbols() -> usize {
    unsafe extern "C" fn one(_: *const std::ffi::c_void) -> usize {
        1
    }
    let mut ops = malloc_size_of::MallocSizeOfOps::new(one, None, None);
    // Each entry reports two allocations: the entry and its text.
    string_cache::malloc_size_of_dynamic_set(&mut ops) / 2
}

impl From<&str> for Symbol {
    fn from(text: &str) -> Self {
        Symbol::new(text)
    }
}

impl From<Cow<'_, str>> for Symbol {
    fn from(text: Cow<'_, str>) -> Self {
        Symbol::new(&text)
    }
}

/// Construct a compile-time symbol from trunk-ir's registered literal names.
///
/// ```
/// use trunk_ir::{symbol, Symbol};
/// const FUNC: Symbol = symbol!("func");
/// assert_eq!(FUNC, Symbol::new("func"));
/// ```
///
/// Runtime names use `Symbol::new` instead:
///
/// ```compile_fail
/// use trunk_ir::symbol;
/// let name = String::from("func");
/// let _ = symbol!(name);
/// ```
#[macro_export]
macro_rules! symbol {
    ($name:ident) => {
        compile_error!(
            "symbol! requires a registered string literal; use Symbol::new for runtime names"
        )
    };
    ($text:tt) => {
        $crate::Symbol::__from_atom($crate::symbol::atom::literal!($text))
    };
}

/// Helper macro for declaring multiple symbol helpers at once.
///
/// # Example
/// ```
/// use trunk_ir::symbols;
///
/// symbols! {
///     ATTR_NAME => "name",
///     ATTR_TYPE => "type",
///     #[allow(dead_code)]
///     ATTR_UNUSED => "unused",
/// }
/// ```
#[macro_export]
macro_rules! symbols {
    ($($(#[$attr:meta])* $name:ident => $text:literal),* $(,)?) => {
        $(
            $(#[$attr])*
            #[allow(non_snake_case)]
            #[inline]
            pub fn $name() -> $crate::Symbol {
                $crate::Symbol::new($text)
            }
        )*
    };
}

impl PartialEq<&Symbol> for Symbol {
    fn eq(&self, other: &&Symbol) -> bool {
        self == *other
    }
}

impl PartialEq<Symbol> for &Symbol {
    fn eq(&self, other: &Symbol) -> bool {
        *self == other
    }
}

// Convenient comparison with &str
impl PartialEq<str> for Symbol {
    fn eq(&self, other: &str) -> bool {
        self.with_str(|s| s == other)
    }
}

impl PartialEq<&str> for Symbol {
    fn eq(&self, other: &&str) -> bool {
        self.with_str(|s| s == *other)
    }
}

impl PartialEq<Symbol> for str {
    fn eq(&self, other: &Symbol) -> bool {
        other.with_str(|s| s == self)
    }
}

impl PartialEq<Symbol> for &str {
    fn eq(&self, other: &Symbol) -> bool {
        other.with_str(|s| s == *self)
    }
}

// For Display (uses with_str for zero-copy)
impl std::fmt::Display for Symbol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.with_str(|s| write!(f, "{}", s))
    }
}

// ============================================================================
// Symbol paths
// ============================================================================

/// The name of a symbol table definition: the names of its enclosing modules
/// below the root, then its own name.
///
/// Each component is one name, taken as it is: a name that contains `::` is
/// still a single component, so a path built from one qualified name differs
/// from the path that spells the same text as nested modules. Up to two
/// components are stored inline.
#[derive(Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SymbolPath(SmallVec<[Symbol; 2]>);

impl SymbolPath {
    /// The separator between components in the textual form.
    pub const SEPARATOR: &'static str = "::";

    /// A path from its components, outermost module first.
    ///
    /// # Panics
    ///
    /// Panics if `components` is empty.
    pub fn new(components: impl IntoIterator<Item = impl Into<Symbol>>) -> Self {
        let components: SmallVec<[Symbol; 2]> = components.into_iter().map(Into::into).collect();
        assert!(!components.is_empty(), "a symbol path has a component");
        SymbolPath(components)
    }

    /// The path of the definition named `name` inside the modules `modules`.
    pub fn in_modules(modules: &[Symbol], name: Symbol) -> Self {
        let mut components: SmallVec<[Symbol; 2]> = modules.iter().cloned().collect();
        components.push(name);
        SymbolPath(components)
    }

    pub fn components(&self) -> &[Symbol] {
        &self.0
    }

    /// The definition's own name, without its modules.
    pub fn leaf(&self) -> &Symbol {
        self.0.last().expect("a symbol path has a component")
    }

    /// The enclosing modules, outermost first.
    pub fn modules(&self) -> &[Symbol] {
        &self.0[..self.0.len() - 1]
    }

    /// The name of a definition directly in the root module.
    pub fn as_simple(&self) -> Option<&Symbol> {
        match self.0.as_slice() {
            [name] => Some(name),
            _ => None,
        }
    }

    /// Whether the path has no enclosing module.
    pub fn is_simple(&self) -> bool {
        self.0.len() == 1
    }

    /// The components joined into one symbol, as [`Display`](std::fmt::Display)
    /// writes them.
    pub fn to_symbol(&self) -> Symbol {
        match self.as_simple() {
            Some(name) => name.clone(),
            None => Symbol::new(&self.to_string()),
        }
    }
}

/// Joins the components with `::`. The result does not tell a component that
/// contains `::` from nested modules; the IR printer writes each component
/// separately.
impl std::fmt::Display for SymbolPath {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for (index, component) in self.0.iter().enumerate() {
            if index != 0 {
                f.write_str(Self::SEPARATOR)?;
            }
            f.write_str(component.as_str())?;
        }
        Ok(())
    }
}

impl std::fmt::Debug for SymbolPath {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SymbolPath")?;
        f.debug_list()
            .entries(self.0.iter().map(Symbol::as_str))
            .finish()
    }
}

/// A single name is the path of a definition in the root module.
impl From<Symbol> for SymbolPath {
    fn from(name: Symbol) -> Self {
        SymbolPath(smallvec::smallvec![name])
    }
}

impl From<&Symbol> for SymbolPath {
    fn from(name: &Symbol) -> Self {
        SymbolPath::from(name.clone())
    }
}

impl From<&str> for SymbolPath {
    fn from(name: &str) -> Self {
        SymbolPath::from(Symbol::new(name))
    }
}

impl From<&SymbolPath> for SymbolPath {
    fn from(path: &SymbolPath) -> Self {
        path.clone()
    }
}

/// A path equals a name when it is that name in the root module.
impl PartialEq<str> for SymbolPath {
    fn eq(&self, other: &str) -> bool {
        self.as_simple().is_some_and(|name| name == other)
    }
}

impl PartialEq<&str> for SymbolPath {
    fn eq(&self, other: &&str) -> bool {
        *self == **other
    }
}

impl PartialEq<SymbolPath> for str {
    fn eq(&self, other: &SymbolPath) -> bool {
        other == self
    }
}

impl PartialEq<SymbolPath> for &str {
    fn eq(&self, other: &SymbolPath) -> bool {
        other == *self
    }
}

impl PartialEq<Symbol> for SymbolPath {
    fn eq(&self, other: &Symbol) -> bool {
        self.as_simple() == Some(other)
    }
}

impl PartialEq<Symbol> for &SymbolPath {
    fn eq(&self, other: &Symbol) -> bool {
        **self == *other
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Matching a typed operation builds its dialect and operation names, so
    /// those must not reach the dynamic set.
    #[test]
    fn declared_operation_names_are_static() {
        let mut dynamic = Vec::new();
        for crate::op_def::OpDefRegistration(def) in
            inventory::iter::<crate::op_def::OpDefRegistration>
        {
            let schema = &def.schema;
            let attributes = schema.attributes.iter().map(|attribute| attribute.name);
            for name in [schema.dialect, schema.name].into_iter().chain(attributes) {
                if !Symbol::new(name).is_static_or_inline() {
                    dynamic.push(format!("{}.{}: {name}", schema.dialect, schema.name));
                }
            }
        }
        assert!(dynamic.is_empty(), "{dynamic:#?}");
    }

    #[test]
    fn symbol_paths_keep_each_name_as_one_component() {
        let path = SymbolPath::new(["outer", "inner", "same"]);
        assert_eq!(path.components().len(), 3);
        assert_eq!(path.leaf(), "same");
        assert_eq!(path.modules(), [Symbol::new("outer"), Symbol::new("inner")]);
        assert_eq!(path.to_string(), "outer::inner::same");
        assert_eq!(path.as_simple(), None);

        // A qualified name is one component, not the modules it spells.
        let flat = SymbolPath::from("outer::inner::same");
        assert!(flat.is_simple());
        assert_eq!(flat, "outer::inner::same");
        assert_ne!(flat, path);
        assert_ne!(path, "outer::inner::same");
        assert_eq!(flat.to_symbol(), path.to_symbol());

        assert_eq!(
            SymbolPath::in_modules(path.modules(), Symbol::new("same")),
            path
        );
        let root = SymbolPath::from("a");
        assert!(root < SymbolPath::new(["a", "b"]));
        assert_eq!(std::mem::size_of::<SymbolPath>(), 24);
        assert_eq!(std::mem::size_of::<crate::types::Attribute>(), 32);
    }

    #[test]
    fn symbols_compare_and_order_by_text() {
        let short = Symbol::new("short");
        let text = String::from("a_name_longer_than_seven_bytes");
        let long = Symbol::new(&text);
        assert_eq!(long, Symbol::new(&text));
        assert_eq!(long, "a_name_longer_than_seven_bytes");
        assert!(long < short);
        assert!(short.is_static_or_inline());
        assert!(!long.is_static_or_inline());
    }
}

// ============================================================================
// Block Identity
// ============================================================================

/// Global counter for generating unique block IDs.
static NEXT_BLOCK_ID: AtomicU64 = AtomicU64::new(1);

/// Stable block identifier that survives block recreation.
///
/// Unlike `Block` (which is a Salsa tracked struct with identity tied to creation),
/// `BlockId` is a simple u64 that can be preserved when a block is recreated
/// during IR transformations. This allows block arguments to maintain stable
/// identity across rewrites.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct BlockId(pub u64);

impl BlockId {
    /// Generate a fresh unique block ID.
    pub fn fresh() -> Self {
        BlockId(NEXT_BLOCK_ID.fetch_add(1, Ordering::Relaxed))
    }
}

// ============================================================================
// Small vector type aliases
// ============================================================================

/// Small vector for values tracked by Salsa framework.
pub type IdVec<T> = SmallVec<[T; 2]>;

/// Small vector for symbols.
pub type SymbolVec = SmallVec<[Symbol; 4]>;
