//! Arena dialect operation and type utilities.
//!
//! Provides `DialectOp` and `ArenaDialectType` traits for arena-based
//! dialect operation and type wrappers.
//! Definitions are now generated by `trunk_ir_macros::arena_dialect!`.

use super::context::IrContext;
use super::refs::{OpRef, TypeRef};
use crate::ops::ConversionError;

/// Trait for arena-based dialect operation wrappers.
pub trait DialectOp: Sized + Copy {
    const DIALECT_NAME: &'static str;
    const OP_NAME: &'static str;

    fn from_op(ctx: &IrContext, op: OpRef) -> Result<Self, ConversionError>;
    fn op_ref(&self) -> OpRef;

    fn matches(ctx: &IrContext, op: OpRef) -> bool {
        let data = ctx.op(op);
        data.dialect == crate::Symbol::new(Self::DIALECT_NAME)
            && data.name == crate::Symbol::new(Self::OP_NAME)
    }
}

/// Trait for arena-based dialect type wrappers.
pub trait ArenaDialectType: Sized + Copy {
    const DIALECT_NAME: &'static str;
    const TYPE_NAME: &'static str;

    fn from_type_ref(ctx: &IrContext, ty: TypeRef) -> Option<Self>;
    fn as_type_ref(&self) -> TypeRef;

    fn matches(ctx: &IrContext, ty: TypeRef) -> bool {
        let data = ctx.types.get(ty);
        data.dialect == crate::Symbol::new(Self::DIALECT_NAME)
            && data.name == crate::Symbol::new(Self::TYPE_NAME)
    }
}
