//! Arena dialect operation utilities.
//!
//! Provides `ArenaDialectOp` trait for arena-based dialect operation wrappers.
//! Operation definitions are now generated by `trunk_ir_macros::arena_dialect!`.

use super::context::IrContext;
use super::refs::OpRef;
use crate::ops::ConversionError;

/// Trait for arena-based dialect operation wrappers.
pub trait ArenaDialectOp: Sized + Copy {
    const DIALECT_NAME: &'static str;
    const OP_NAME: &'static str;

    fn from_op(ctx: &IrContext, op: OpRef) -> Result<Self, ConversionError>;
    fn op_ref(&self) -> OpRef;

    fn matches(ctx: &IrContext, op: OpRef) -> bool {
        let data = ctx.op(op);
        data.dialect == crate::Symbol::new(Self::DIALECT_NAME)
            && data.name == crate::Symbol::new(Self::OP_NAME)
    }
}
