[package]
name = "tribute-ir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Tribute language-specific IR dialects"

[dependencies]
hashbrown.workspace = true
derive_more.workspace = true
inventory.workspace = true
itertools.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true
tribute-rc.workspace = true
trunk-ir.workspace = true
winnow.workspace = true

[dev-dependencies]
