id = "tribute-lang"
name = "Tribute Language"
version = "0.1.0"
schema_version = 1
description = "Tribute language support for Zed"
repository = "https://github.com/Kroisse/tribute"
authors = ["Eunchong Yu <kroisse@gmail.com>"]

[grammars.tribute]
repository = "https://github.com/Kroisse/tree-sitter-tribute"
rev = "d88ae0cefc5da2a7891042d84d39c2b6985d62c0"

[language_servers.tribute-lsp]
name = "Tribute Language Server"
languages = ["Tribute"]
