id = "tribute-lang"
name = "Tribute Language"
version = "0.1.0"
schema_version = 1
description = "Tribute language support for Zed"
repository = "https://github.com/Kroisse/tribute"
authors = ["Eunchong Yu <kroisse@gmail.com>"]

[grammars.tribute]
repository = "https://github.com/Kroisse/tree-sitter-tribute"
rev = "40c521d20856e95179079ebe23f7a06a9841b9a1"

[language_servers.tribute-lsp]
name = "Tribute Language Server"
languages = ["Tribute"]
